### ISSUE TITLE
benchmark(with react-hooks and react-redux-hooks)

### ISSUE THREAD

**Issue by chemdemo** [react-kit/hookstore#2]
Test source code: https://github.com/react-kit/js-framework-benchmark/blob/master/frameworks/keyed/hookstore/src/main.jsx

Result(test with react-hooks, react-redux-hooks):

**Duration in milliseconds ± 95% confidence interval (Slowdown = Duration / Fastest)**

![image](https://user-images.githubusercontent.com/1014734/68119939-05646980-ff3f-11e9-9481-ed539ea76ac7.png)

**Startup metrics (lighthouse with mobile simulation)**

![image](https://user-images.githubusercontent.com/1014734/68119932-fd0c2e80-ff3e-11e9-9a3f-358f462dd2fb.png)

**Memory allocation in MBs ± 95% confidence interval**

![image](https://user-images.githubusercontent.com/1014734/68119917-eebe1280-ff3e-11e9-9479-14102bdba75c.png)

**Comment by fengsx** [comment]
💪💪
